import { Injectable } from '@nestjs/common';
import { PaymentAttempt, PaymentAttemptStatus, Prisma } from '@prisma/client';

export interface NewPaymentAttempt {
  /** File 12 Part 50: pre-generated by the caller so the same id can be sent to the gateway as its "merchant reference" before this row exists — same circular-FK pattern `ConfirmAppointmentUseCase` already uses for `Appointment.id` (Part 36.4). */
  id: string;
  paymentIntentId: string;
  gatewayReference?: string;
  metadata?: Prisma.InputJsonValue;
}

@Injectable()
export class PaymentAttemptRepository {
  create(db: Prisma.TransactionClient, input: NewPaymentAttempt): Promise<PaymentAttempt> {
    return db.paymentAttempt.create({
      data: {
        id: input.id,
        payment_intent_id: input.paymentIntentId,
        gateway_reference: input.gatewayReference,
        metadata: input.metadata,
      },
    });
  }

  findByGatewayReference(db: Prisma.TransactionClient, gatewayReference: string): Promise<PaymentAttempt | null> {
    return db.paymentAttempt.findFirst({ where: { gateway_reference: gatewayReference }, orderBy: { created_at: 'desc' } });
  }

  async updateStatus(
    db: Prisma.TransactionClient,
    id: string,
    status: PaymentAttemptStatus,
    fields?: { failureCode?: string; metadata?: Prisma.InputJsonValue },
  ): Promise<void> {
    await db.paymentAttempt.update({
      where: { id },
      data: { status, failure_code: fields?.failureCode, metadata: fields?.metadata },
    });
  }
}
