import { Injectable } from '@nestjs/common';
import { Prisma, WalletTransaction, WalletTransactionStatus, WalletTransactionType } from '@prisma/client';

export interface NewWalletTransaction {
  /** Pre-generated by the caller when it must be referenced (as `PaymentIntent.payable_id`) before this row exists — same pattern as `Appointment.id` (File 12 Part 36.4). */
  id?: string;
  walletId: string;
  type: WalletTransactionType;
  amount: string;
  status?: WalletTransactionStatus;
  resultingBalance?: string;
  paymentIntentId?: string;
  appointmentId?: string;
  idempotencyKey?: string;
}

export interface ListWalletTransactionsParams {
  walletId: string;
  cursor?: { createdAt: string; id: string };
  limit: number;
}

@Injectable()
export class WalletTransactionRepository {
  create(db: Prisma.TransactionClient, input: NewWalletTransaction): Promise<WalletTransaction> {
    return db.walletTransaction.create({
      data: {
        id: input.id,
        wallet_id: input.walletId,
        type: input.type,
        status: input.status ?? 'PENDING',
        amount: input.amount,
        resulting_balance: input.resultingBalance,
        payment_intent_id: input.paymentIntentId,
        appointment_id: input.appointmentId,
        idempotency_key: input.idempotencyKey,
      },
    });
  }

  findByIdempotencyKey(db: Prisma.TransactionClient, idempotencyKey: string): Promise<WalletTransaction | null> {
    return db.walletTransaction.findUnique({ where: { idempotency_key: idempotencyKey } });
  }

  findByPaymentIntentId(db: Prisma.TransactionClient, paymentIntentId: string): Promise<WalletTransaction | null> {
    return db.walletTransaction.findFirst({ where: { payment_intent_id: paymentIntentId } });
  }

  /** `false` means a concurrent writer already resolved this transaction — a duplicate webhook's second delivery, caught here as a defense-in-depth layer behind the `webhook_events` idempotency insert. */
  async markCompleted(db: Prisma.TransactionClient, id: string, resultingBalance: string): Promise<boolean> {
    const result = await db.walletTransaction.updateMany({
      where: { id, status: 'PENDING' },
      data: { status: 'COMPLETED', resulting_balance: resultingBalance },
    });
    return result.count === 1;
  }

  async markFailed(db: Prisma.TransactionClient, id: string, failureReason: string): Promise<boolean> {
    const result = await db.walletTransaction.updateMany({
      where: { id, status: 'PENDING' },
      data: { status: 'FAILED', failure_reason: failureReason },
    });
    return result.count === 1;
  }

  list(db: Prisma.TransactionClient, params: ListWalletTransactionsParams): Promise<WalletTransaction[]> {
    return db.walletTransaction.findMany({
      where: {
        wallet_id: params.walletId,
        ...(params.cursor && {
          OR: [
            { created_at: { lt: new Date(params.cursor.createdAt) } },
            { created_at: new Date(params.cursor.createdAt), id: { lt: params.cursor.id } },
          ],
        }),
      },
      orderBy: [{ created_at: 'desc' }, { id: 'desc' }],
      take: params.limit,
    });
  }
}
