import { Injectable } from '@nestjs/common';
import { Appointment, AppointmentStatus, Prisma } from '@prisma/client';

export interface NewAppointment {
  /** File 12 Part 36.4: pre-generated by the caller so the same UUID can be used as `PaymentIntent.payable_id` before this row exists. */
  id?: string;
  slotId: string;
  patientId: string;
  doctorClinicAffiliationId: string;
  /** File 12 Part 35.10/35.13: set when this confirm originated from a reschedule's hold. */
  rescheduledFromAppointmentId?: string;
  /** File 12 Part 36: set once pay-at-clinic capture succeeds in the same transaction. */
  paymentIntentId?: string;
}

const WITH_SLOT_TIMES = {
  slot: { select: { start_at: true, end_at: true } },
  affiliation: {
    select: {
      doctor: { select: { id: true, user: { select: { first_name: true, last_name: true } } } },
      clinic_branch: {
        select: {
          id: true,
          phone: true,
          clinic: { select: { brand_name: true } },
          address: { select: { line1: true, city: true } },
        },
      },
    },
  },
} satisfies Prisma.AppointmentInclude;

/**
 * File 12 Part 35.15/35.17: list/detail need the slot's timing to render.
 * `doctor_clinic_affiliation` (and its `doctor`/`clinic_branch`) is a
 * same-request read of another module's tables for display purposes only
 * (doctor name, clinic name/address) — not a cross-module *write* or a
 * business-rule dependency, so it doesn't violate Part 33.3's "no
 * cross-module joins for business logic" rule the same way a WHERE-clause
 * join would.
 */
export type AppointmentWithSlotTimes = Prisma.AppointmentGetPayload<{ include: typeof WITH_SLOT_TIMES }>;

/**
 * File 12 Part 49.7 — the doctor-facing view. Kept as a *separate* include
 * from `WITH_SLOT_TIMES` on purpose: the patient list/detail path must not
 * start paying for a `users` join it never renders, and the patient's phone
 * number must not become reachable from a response shape a patient can ask
 * for. `iana_timezone` is added here because the Doctor Dashboard renders a
 * clinic-local day view and would otherwise have to guess the offset.
 */
const WITH_DOCTOR_VIEW = {
  slot: { select: { start_at: true, end_at: true } },
  patient: { select: { id: true, first_name: true, last_name: true, phone: true } },
  affiliation: {
    select: {
      doctor: { select: { id: true, user: { select: { first_name: true, last_name: true } } } },
      clinic_branch: {
        select: {
          id: true,
          phone: true,
          iana_timezone: true,
          clinic: { select: { id: true, brand_name: true } },
          address: { select: { line1: true, city: true } },
        },
      },
    },
  },
} satisfies Prisma.AppointmentInclude;

export type AppointmentWithDoctorView = Prisma.AppointmentGetPayload<{ include: typeof WITH_DOCTOR_VIEW }>;

export interface ListAppointmentsForPatientParams {
  patientId: string;
  status?: AppointmentStatus;
  from?: Date;
  to?: Date;
  cursor?: { startAt: string; id: string };
  limit: number;
}

/**
 * File 12 Part 49.7. `affiliationIds` is resolved server-side from the
 * caller's JWT (`ResolveDoctorScopeUseCase`) — it is never a client-supplied
 * filter, which is what makes this list impossible to widen from the
 * outside. A `clinicBranchId` request filter is applied by *narrowing this
 * array* in the use-case rather than adding a `where` clause, so the branch
 * filter can only ever shrink an already-JWT-derived set.
 */
export interface ListAppointmentsForDoctorParams {
  affiliationIds: string[];
  status?: AppointmentStatus;
  from?: Date;
  to?: Date;
  cursor?: { startAt: string; id: string };
  limit: number;
}

/**
 * Both bounds have to go into **one** `start_at` object. Spreading them as
 * two conditional keys (`...(from && { start_at: { gte } })`,
 * `...(to && { start_at: { lt } })`) silently drops the first whenever both
 * are supplied — the second key overwrites it — so a `from`+`to` range
 * filter degraded into a `to`-only filter. Fixed in File 12 Part 49.7 while
 * adding the doctor-facing list, which sends both bounds for its day view;
 * the patient list shared the same defect and is fixed by the same helper.
 */
function slotStartAtFilter(from?: Date, to?: Date): Prisma.AppointmentSlotWhereInput | undefined {
  if (!from && !to) {
    return undefined;
  }
  return { start_at: { ...(from && { gte: from }), ...(to && { lt: to }) } };
}

@Injectable()
export class AppointmentRepository {
  /** File 12 Part 35.1: created at confirm time, straight to `CONFIRMED`. Part 36: `payment_intent_id` is populated once pay-at-clinic capture succeeds in the same transaction. */
  create(db: Prisma.TransactionClient, input: NewAppointment): Promise<Appointment> {
    return db.appointment.create({
      data: {
        id: input.id,
        slot_id: input.slotId,
        patient_id: input.patientId,
        doctor_clinic_affiliation_id: input.doctorClinicAffiliationId,
        status: 'CONFIRMED',
        rescheduled_from_appointment_id: input.rescheduledFromAppointmentId,
        payment_intent_id: input.paymentIntentId,
      },
    });
  }

  findById(db: Prisma.TransactionClient, id: string): Promise<Appointment | null> {
    return db.appointment.findUnique({ where: { id } });
  }

  /** File 12 Part 35.16: detail's "full detail" — the `Appointment` row plus its slot's timing. */
  findByIdWithSlotTimes(db: Prisma.TransactionClient, id: string): Promise<AppointmentWithSlotTimes | null> {
    return db.appointment.findUnique({ where: { id }, include: WITH_SLOT_TIMES });
  }

  /** File 12 Part 35.15: cursor-paginated on the slot's `(start_at, id)`, always scoped to one patient (Part 35.14). */
  listForPatient(db: Prisma.TransactionClient, params: ListAppointmentsForPatientParams): Promise<AppointmentWithSlotTimes[]> {
    return db.appointment.findMany({
      where: {
        patient_id: params.patientId,
        ...(params.status && { status: params.status }),
        ...(slotStartAtFilter(params.from, params.to) && { slot: slotStartAtFilter(params.from, params.to) }),
        ...(params.cursor && {
          OR: [
            { slot: { start_at: { gt: new Date(params.cursor.startAt) } } },
            { slot: { start_at: new Date(params.cursor.startAt) }, id: { gt: params.cursor.id } },
          ],
        }),
      },
      include: WITH_SLOT_TIMES,
      orderBy: [{ slot: { start_at: 'asc' } }, { id: 'asc' }],
      take: params.limit,
    });
  }

  /** File 12 Part 49.7: doctor-facing detail — same row plus the patient identity the provider legitimately needs. */
  findByIdWithDoctorView(db: Prisma.TransactionClient, id: string): Promise<AppointmentWithDoctorView | null> {
    return db.appointment.findUnique({ where: { id }, include: WITH_DOCTOR_VIEW });
  }

  /**
   * File 12 Part 49.7: the Doctor Dashboard queue. Same `(slot.start_at, id)`
   * cursor shape as `listForPatient` (Part 35.15) so both surfaces paginate
   * identically; the only difference is the scoping predicate —
   * `doctor_clinic_affiliation_id IN (caller's own affiliations)` rather
   * than `patient_id = caller`.
   */
  listForDoctor(db: Prisma.TransactionClient, params: ListAppointmentsForDoctorParams): Promise<AppointmentWithDoctorView[]> {
    if (params.affiliationIds.length === 0) {
      return Promise.resolve([]);
    }

    return db.appointment.findMany({
      where: {
        doctor_clinic_affiliation_id: { in: params.affiliationIds },
        ...(params.status && { status: params.status }),
        ...(slotStartAtFilter(params.from, params.to) && { slot: slotStartAtFilter(params.from, params.to) }),
        ...(params.cursor && {
          OR: [
            { slot: { start_at: { gt: new Date(params.cursor.startAt) } } },
            { slot: { start_at: new Date(params.cursor.startAt) }, id: { gt: params.cursor.id } },
          ],
        }),
      },
      include: WITH_DOCTOR_VIEW,
      orderBy: [{ slot: { start_at: 'asc' } }, { id: 'asc' }],
      take: params.limit,
    });
  }

  /** File 12 Part 35.8: version-guarded `CONFIRMED→CANCELLED`. `false` means the appointment was modified concurrently since the caller read its version. */
  async cancel(db: Prisma.TransactionClient, id: string, currentVersion: number, cancelledBy: string, cancelledReason: string): Promise<boolean> {
    const result = await db.appointment.updateMany({
      where: { id, version: currentVersion, status: 'CONFIRMED' },
      data: { status: 'CANCELLED', cancelled_by: cancelledBy, cancelled_reason: cancelledReason, version: { increment: 1 } },
    });
    return result.count === 1;
  }

  /** File 12 Part 35.10: version-guarded `CONFIRMED→RESCHEDULED`, the old-appointment side of a reschedule. */
  async markRescheduled(db: Prisma.TransactionClient, id: string, currentVersion: number): Promise<boolean> {
    const result = await db.appointment.updateMany({
      where: { id, version: currentVersion, status: 'CONFIRMED' },
      data: { status: 'RESCHEDULED', version: { increment: 1 } },
    });
    return result.count === 1;
  }
}
